Oxit.Web.Admin/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Oxit.DataAccess.EntityFramework;
using Oxit.DataAccess.teknopark;
using System.Diagnostics;
using System.Transactions;
using Oxit.Domain.Models;

namespace Oxit.Web.Admin.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly TeknoparkContext _db;
        private readonly IConfiguration _configuration;
        private readonly appDbContext _appDbContext;

        public CompaniesController(
            IConfiguration configuration,
            appDbContext appDbContext,
            TeknoparkContext db
            )
        {
            _configuration = configuration;
            _db = db;
            _appDbContext = appDbContext;
        }
        public IActionResult Index(string name, string kod)
        {
            List<HesapPlaniDto> firmalar = _appDbContext.HesapPlani
                .Select(x => new HesapPlaniDto
                {
                    Id = x.Id,
                    Ad = x.Ad,
                    Kod = x.Kod,
                    Borc =    Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.FisTur != "6" && y.HesapPlani.Aktif).Sum(y => y.Borc)),
                    Alacak =    Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.HesapPlani.Aktif && y.FisTur != "6").Sum(y => y.Alacak)),
                    Bakiye = Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.HesapPlani.Aktif && y.FisTur != "6").Sum(y => y.Borc))  - Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.FisTur != "6").Sum(y => y.Alacak)),
                    GecikmeTutari = Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.HesapPlani.Aktif).Sum(y => y.GecikmeTutari)),
                    ToplamGecikmeTutari = Convert.ToDouble(_appDbContext.Fis.Where(f => f.HesapPlani.Aktif).Sum(y => y.GecikmeTutari)),
                    ToplamBorcTutari = Convert.ToDouble(_appDbContext.Fis.Where(f => f.HesapPlani.Aktif && f.FisTur != "6").Sum(y => y.Borc)),
                    ToplamAlacakTutari = Convert.ToDouble(_appDbContext.Fis.Where(f => f.HesapPlani.Aktif && f.FisTur != "6").Sum(y => y.Alacak)),
                    Aktif = x.Aktif
                })
                .OrderBy(h => h.Ad)
                .ToList();

            return View(firmalar);
        }

        [HttpPost]
        public EmptyResult SaveStatus(int companyId, bool status)
        {
            var firma = _appDbContext.HesapPlani.Find(companyId);
            firma.Aktif = status;
            _appDbContext.HesapPlani.Update(firma);
            _appDbContext.SaveChanges();
            return new EmptyResult();
        }

    }
}

Oxit.Web.Admin/Controllers/RentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Oxit.DataAccess.EntityFramework;
using Oxit.DataAccess.teknopark;
using System.Diagnostics;
using System.Transactions;
using Oxit.Domain.Models;
using ExcelDataReader;
using System.Reflection;
using Oxit.Core.Utilities;
using Oxit.Domain.ViewModels.Kira;
using AutoMapper;
using Oxit.Domain;

namespace Oxit.Web.Admin.Controllers
{
    public partial class RentsController : Controller
    {
        private readonly TeknoparkContext _db;
        private readonly HesapPlaniService _hesapPlaniService;
        private readonly IConfiguration _configuration;
        private readonly appDbContext _appDbContext;
        private readonly IMapper _mapper;
        private static string AssemblyDirectory
        {
            get
            {
                string codeBase = Assembly.GetExecutingAssembly().CodeBase;
                UriBuilder uri = new UriBuilder(codeBase);
                string path = Uri.UnescapeDataString(uri.Path);
                return Path.GetDirectoryName(path);
            }
        }
        public RentsController(
            IConfiguration configuration,
            appDbContext appDbContext,
            IMapper mapper,
            TeknoparkContext db,
            HesapPlaniService hesapPlaniService
            )
        {
            _configuration = configuration;
            _db = db;
            _hesapPlaniService = hesapPlaniService;
            _appDbContext = appDbContext;
            _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet, ActionName("Upload")]
        public IActionResult Upload_get()
        {
            return View();
        }
        [HttpPost, ActionName("Upload")]
        public async Task<IActionResult> Upload_pot(IFormFile kira)
        {
            if (kira.Length > 0)
            {
                MemoryStream ms = new MemoryStream();
                kira.CopyToAsync(ms);
                var excelData = ms.ExcelToObject<KiraExcel>();

                using (var tra = _appDbContext.Database.BeginTransaction())
                {
                    try
                    {



                        foreach (var item in excelData)
                        {
                            _appDbContext.Kira.Add(new Kira
                            {

                                FirmaAdi = item.FirmaAdi,
                                Aciklama = String.Empty,
                                BaslamaTarihi = DateTime.Parse(item.BaslamaTarihi.Split(" ")[0]),
                                BitisTarihi = DateTime.Parse(item.BitisTarihi.Split(" ")[0]),
                                Metrekare = double.Parse(item.Metrekare),
                                MetrekareIsletmeFiyati = double.Parse(item.IsletmeMetreKareFiyat),
                                MetrekareKiraFiyati = double.Parse(item.KiraMetreKareFiyat),
                                IsletmeBedeli = double.Parse(item.Metrekare) * double.Parse(item.IsletmeMetreKareFiyat),
                                KiraBedeli = double.Parse(item.Metrekare) * double.Parse(item.KiraMetreKareFiyat),
                                IsletmeKDVOrani = 18,
                                KiraKDVOrani = 18,

                            });

                        }
                        _appDbContext.SaveChanges();
                        tra.Commit();
                    }
                    catch (Exception ex)
                    {
                        tra.Rollback();
                        throw;
                    }
                }
            }
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult GetFile()
        {
            return File(new FileStream("files\\kira.xlsx", FileMode.Open), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "kira.xlsx");
        }

        [HttpGet, ActionName("Save")]
        public IActionResult Save_Get(int? Id)
        {
            if (Id == null)
                return View();

            var data = _appDbContext.Kira.Find(Id);
            if (data == null)
                return RedirectToAction("index");
            return View(data);

        }

        [HttpPost, ActionName("Save")]
        public IActionResult Save_Post(KiraSaveDTO model)
        {

            if (model.Id is not null or > 0)
                update(model);
            else
                insert(model);

            return RedirectToAction("index");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            _appDbContext.Kira.Remove(_appDbContext.Kira.Find(Id));
            _appDbContext.SaveChanges();
            return RedirectToAction("index");

        }

        [HttpGet]
        public IActionResult DeleteConfirm(int Id)
        {
            return View(_appDbContext.Kira.Find(Id));

        }

        [HttpGet]
        public JsonResult GetRents(int take, int skip, int page, int pagesize)
        {



            List<KiraReadDTO> kiralar =
                _appDbContext
                .Kira
                .Select(x => new KiraReadDTO
                {
                    Aciklama = x.Aciklama,
                    BaslamaTarihi = x.BaslamaTarihi,
                    BitisTarihi = x.BitisTarihi,
                    FirmaAdi = x.FirmaAdi,
                    Id = x.Id,
                    IsletmeBedeli = x.IsletmeBedeli,
                    IsletmeKDVOrani = x.IsletmeKDVOrani,
                    KiraBedeli = x.KiraBedeli,
                    KiraKDVOrani = x.KiraKDVOrani,
                    Metrekare = x.Metrekare,
                    MetrekareIsletmeFiyati = x.MetrekareIsletmeFiyati,
                    MetrekareKiraFiyati = x.MetrekareKiraFiyati,
                    KalanGun = (x.BitisTarihi.Value - x.BaslamaTarihi.Value).Days

                })
             .OrderBy(h => h.Id)
             .Skip(skip)
             .Take(take)
             .ToList();

            return Json(new
            {
                Data = kiralar,
                Total = _appDbContext.Kira.Count(),
                Page = page,


            });
        }

        private void update(KiraSaveDTO model)
        {
            var oldData = _appDbContext.Kira.Find(model.Id);
            if (oldData != null)
            {
                oldData.FirmaAdi = model.FirmaAdi;
                oldData.Aciklama = model.Aciklama ?? String.Empty;
                oldData.BaslamaTarihi = DateTime.Parse(model.BaslamaTarihi);
                oldData.BitisTarihi = DateTime.Parse(model.BitisTarihi);
                oldData.Metrekare = model.Metrekare;
                oldData.MetrekareIsletmeFiyati = model.MetrekareIsletmeFiyati;
                oldData.MetrekareKiraFiyati = model.MetrekareKiraFiyati;
                oldData.KiraKDVOrani = model.KiraKDVOrani;
                oldData.IsletmeKDVOrani = model.IsletmeKDVOrani;
                oldData.IsletmeBedeli = model.Metrekare * model.MetrekareIsletmeFiyati;
                oldData.KiraBedeli = model.Metrekare * model.MetrekareKiraFiyati;

                _appDbContext.SaveChanges();

            }

        }

        private void insert(KiraSaveDTO model)
        {
            _appDbContext.Kira.Add(new Kira
            {
                FirmaAdi = model.FirmaAdi,
                Aciklama = model.Aciklama ?? String.Empty,
                BaslamaTarihi = DateTime.Parse(model.BaslamaTarihi),
                BitisTarihi = DateTime.Parse(model.BitisTarihi),
                Metrekare = model.Metrekare,
                MetrekareIsletmeFiyati = model.MetrekareIsletmeFiyati,
                MetrekareKiraFiyati = model.MetrekareKiraFiyati,
                IsletmeBedeli = model.Metrekare * model.MetrekareIsletmeFiyati,
                KiraBedeli = model.Metrekare * model.MetrekareKiraFiyati,
                IsletmeKDVOrani = model.IsletmeKDVOrani,
                KiraKDVOrani = model.KiraKDVOrani,
            });
            _appDbContext.SaveChanges();
        }
    }
}

Oxit.Web.Admin/Views/Shared/_Footer.cshtml
<footer class="footer non-printable">
    <div class="ms-auto">Oxit Bilişim Ürünüdür</div>
</footer>

Oxit.Web.Admin/Views/Shared/_Header.cshtml
<header class="header header-sticky mb-4 non-printable">
    <div class="container-fluid non-printable">
        <button class="header-toggler px-md-0 me-md-3 non-printable" type="button" onclick="coreui.Sidebar.getInstance(document.querySelector('#sidebar')).toggle()">
            <svg class="icon icon-lg">
                <use xlink:href="/vendors/coreui/icons/svg/free.svg#cil-menu"></use>
            </svg>
        </button>
        <ul class="header-nav d-none d-md-flex">
        </ul>
        <ul class="header-nav ms-auto">
        </ul>
        <ul class="header-nav ms-3">
            
        </ul>
    </div>
    
    
</header>

Oxit.Web.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="Oxit Bilişim">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>@ViewData["Title"] | Oxit</title>
    <link rel="apple-touch-icon" sizes="57x57" href="/assets/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/assets/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/assets/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/assets/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/assets/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/assets/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/assets/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="/assets/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/assets/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="/vendors/simplebar/css/simplebar.css">
    <link rel="stylesheet" href="/css/vendors/simplebar.css">
    <link href="/css/style.css" rel="stylesheet">
    <link href="/css/examples.css" rel="stylesheet">
    <link rel="stylesheet" href="~/font-awesome/css/font-awesome.css">
    <script src="/css/jquery-3.6.0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>

</head>
<body>
    <partial name="_Sidebar"></partial>
    <div class="wrapper d-flex flex-column min-vh-100 bg-light">
        <partial name="_Header"></partial>
        <div class="body flex-grow-1 px-3">
            <div class="container-lg">
                @RenderBody()
            </div>
        </div>
        <partial name="_Footer"></partial>
    </div>
    <script src="/vendors/coreui/coreui/js/coreui.bundle.min.js"></script>
    <script src="/vendors/simplebar/js/simplebar.min.js"></script>

    @RenderSection("Scripts",required:false)
</body>
</html>

Oxit.Web.Admin/Views/Shared/_Sidebar.cshtml
<div class="sidebar sidebar-dark sidebar-fixed non-printable" id="sidebar">
    <div class="sidebar-brand d-none d-md-flex">
        <img class="sidebar-brand-full"  src="~/assets/img/teknopark-ankara-white.png" width="170" alt="Teknopark Ankara"/>

    </div>
    <ul class="sidebar-nav" data-coreui="navigation" data-simplebar="">
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("index","home")">
                <svg class="nav-icon">
                    <use xlink:href="/vendors/coreui/icons/svg/free.svg#cil-speedometer"></use>
                </svg> Anasayfa
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index","Companies")">
                <span class="nav-icon"><i class="fa fa-user"></i></span>
                Kira Takibi
            </a>
        @* </li> *@
        @*    <li class="nav-item"> *@
        @*     <a class="nav-link" href="@Url.Action("Index","Rents")"> *@
        @*         <span class="nav-icon"><i class="fa fa-money"></i></span> *@
        @*         Kiralar *@
        @*     </a> *@
        @* </li> *@

    </ul>
    <button class="sidebar-toggler" type="button" data-coreui-toggle="unfoldable"></button>
</div>