Oxit.Web.Admin/Controllers/CariController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Oxit.DataAccess.EntityFramework;
using Oxit.DataAccess.teknopark;
using System.Diagnostics;
using System.Transactions;
using OfficeOpenXml;
using Oxit.Domain.Models;

namespace Oxit.Web.Admin.Controllers
{
    public class CariController : Controller
    {
        private readonly TeknoparkContext _db;
        private readonly IConfiguration _configuration;
        private readonly appDbContext _appDbContext;
        
        public CariController(
            IConfiguration configuration,
            appDbContext appDbContext,
            TeknoparkContext db
            )
        {
            _configuration = configuration;
            _db = db;
            _appDbContext = appDbContext;
           
        }
        public IActionResult Index(int? hesapId, int? page)
        {
            return View(commonParams(hesapId, page));
        }

        public IActionResult Edit(int? hesapId, int? page)
        {
            return View(commonParams(hesapId, page));
        }
        
        public IActionResult detailData(int alacakId)
        {
            return View(commonParamsDetails(alacakId));
        }
        
        [HttpPost]
        public EmptyResult SaveStatus(int fisId, int status)
        {
            var fis = _appDbContext.Fis.Find(fisId);
            fis.FisTip = (FisTip) status;
            _appDbContext.Fis.Update(fis);
            _appDbContext.SaveChanges();
            return new EmptyResult();
        }

        private Dictionary<string, object> commonParams(int? hesapId, int? page)
        {
            int totalCount = _appDbContext.Fis.Where(f => f.HesapPlani.Id == hesapId).Count();
            int recordsPerPage = 500;
            if (page == null)
                page = 1;
            int skip = (page.Value * recordsPerPage) - recordsPerPage;

            List<Fis> fisList = _appDbContext.Fis
                .Where(f => f.HesapPlani.Id == hesapId )
                .OrderByDescending(h => h.Tarih)
                .Skip(skip)
                .Take(recordsPerPage)
                .ToList();
            
            HesapPlani hesapPlani = _appDbContext.HesapPlani.FirstOrDefault(i => i.Id == hesapId);
            Dictionary<string, object> model = new Dictionary<string, object>();
            model["hesapPlani"] = hesapPlani;
            model["fisList"] = fisList;
            model["page"] = page;
            model["pageCount"] = (totalCount + recordsPerPage - 1) / recordsPerPage;

            return model;
        }
        
        // List<Fis> fisList = 
        //     _appDbContext.Fis
        //         .Where(f => f.GecikmeFisId == alacakId && (f.KalanBorcTutar != f.Borc  || f.OdenenGecikmeTutar > 0 ))
        //         .OrderByDescending(h => h.Tarih)
        //         .ToList();
        //   
        // Dictionary<string, object> model = new Dictionary<string, object>();
        //
        // model["fisList"] = fisList;

        
        
        private Dictionary<string, object> commonParamsDetails(int? alacakId)
        {
            List<Fis> fisList = 
                _appDbContext.Fis
                .Where(f => f.GecikmeFisId == alacakId && (f.KalanBorcTutar != f.Borc  || f.OdenenGecikmeTutar > 0 ))
                .OrderByDescending(h => h.Tarih)
                .ToList();
          
            Dictionary<string, object> model = new Dictionary<string, object>();
       
            model["fisList"] = fisList;
     
            return model;
        }
        
        
        public IActionResult DownloadExcel(int hesapId)
        {
            List<Fis> fisList = _appDbContext.Fis
                .Where(f => f.HesapPlani.Id == hesapId)
                .OrderByDescending(h => h.Tarih)
                .ToList();

            List<FisDto> list = new List<FisDto>();
            foreach (var item in fisList)
            {
                HesapPlani hesapPlani = _appDbContext.HesapPlani.FirstOrDefault(i => i.Id == hesapId);
                list.Add(new FisDto(){ FirmaAdi = hesapPlani.Ad,
                    CariKodu = hesapPlani.Kod,
                    Aciklama = item.Aciklama,
                    Borc = item.Borc,
                    Alacak = item.Alacak,
                    GecikmeTutari = item.GecikmeTutari,
                    GecikenGun = item.GecikmeGunu
                });
            }
            
            var stream = new MemoryStream();
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (var package = new ExcelPackage(stream))
            {
                var workSheet = package.Workbook.Worksheets.Add("Sheet1");
                workSheet.Cells.LoadFromCollection(list, true);
                package.Save();
            }
            stream.Position = 0;
            string excelName = $"{list.First().FirmaAdi} - {DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";
            return File(stream, "application/octet-stream", excelName);  
            //return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
        }
    }
}

Oxit.Web.Admin/Controllers/CompaniesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Oxit.DataAccess.EntityFramework;
using Oxit.DataAccess.teknopark;
using System.Diagnostics;
using System.Transactions;
using Oxit.Domain.Models;

namespace Oxit.Web.Admin.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly TeknoparkContext _db;
        private readonly IConfiguration _configuration;
        private readonly appDbContext _appDbContext;

        public CompaniesController(
            IConfiguration configuration,
            appDbContext appDbContext,
            TeknoparkContext db
            )
        {
            _configuration = configuration;
            _db = db;
            _appDbContext = appDbContext;
        }
        public IActionResult Index(string name, string kod)
        {
            List<HesapPlaniDto> firmalar = _appDbContext.HesapPlani
                .Select(x => new HesapPlaniDto
                {
                    Id = x.Id,
                    Ad = x.Ad,
                    Kod = x.Kod,
                    Borc =    Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.FisTur != "6" && y.HesapPlani.Aktif).Sum(y => y.Borc)),
                    Alacak =    Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.HesapPlani.Aktif && y.FisTur != "6").Sum(y => y.Alacak)),
                    Bakiye = Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.HesapPlani.Aktif && y.FisTur != "6").Sum(y => y.Borc))  - Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.FisTur != "6").Sum(y => y.Alacak)),
                    GecikmeTutari = Convert.ToDouble(_appDbContext.Fis.Where(y => y.HesapPlaniId == x.Id && y.HesapPlani.Aktif).Sum(y => y.GecikmeTutari)),
                    ToplamGecikmeTutari = Convert.ToDouble(_appDbContext.Fis.Where(f => f.HesapPlani.Aktif).Sum(y => y.GecikmeTutari)),
                    ToplamBorcTutari = Convert.ToDouble(_appDbContext.Fis.Where(f => f.HesapPlani.Aktif && f.FisTur != "6").Sum(y => y.Borc)),
                    ToplamAlacakTutari = Convert.ToDouble(_appDbContext.Fis.Where(f => f.HesapPlani.Aktif && f.FisTur != "6").Sum(y => y.Alacak)),
                    Aktif = x.Aktif
                })
                .OrderBy(h => h.Ad)
                .ToList();

            return View(firmalar);
        }

        [HttpPost]
        public EmptyResult SaveStatus(int companyId, bool status)
        {
            var firma = _appDbContext.HesapPlani.Find(companyId);
            firma.Aktif = status;
            _appDbContext.HesapPlani.Update(firma);
            _appDbContext.SaveChanges();
            return new EmptyResult();
        }

    }
}

Oxit.Web.Admin/Controllers/GecikmeHesaplaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Oxit.DataAccess.EntityFramework;
using Oxit.Domain;

namespace Oxit.Web.Admin.Controllers
{
    [Route("api/[controller]")]
    public class GecikmeHesaplaController : Controller
    {
        private readonly appDbContext _appDbContext;
        private readonly IConfiguration _configuration;
        private readonly HesapPlaniService _hesapPlaniService;

        public GecikmeHesaplaController(IConfiguration configuration, appDbContext appDbContext, HesapPlaniService hesapPlaniService)
        {
            _appDbContext = appDbContext;
            _configuration = configuration;
            _hesapPlaniService = hesapPlaniService;
        }

        [HttpGet("GecikmeleriHesaplaBakiye")]
        public EmptyResult GecikmeleriHesaplaBakiye(string hesapKodu)
        {
            _hesapPlaniService.GecikmeleriHesaplaBakiye(hesapKodu);

            return new EmptyResult();
        }
        
        [HttpGet("GecikmeleriHesapla")]
        public EmptyResult GecikmeleriHesapla(string hesapKodu)
        {
            _hesapPlaniService.GecikmeleriHesapla(hesapKodu);

            return new EmptyResult();
        }

        [HttpGet("AlacaksizGecikmeHesapla")]
        public EmptyResult AlacaksizGecikmeHesapla(string hesapKodu)
        {
            _hesapPlaniService.AlacaksizGecikmeHesapla(hesapKodu);
            return new EmptyResult();
        }


        [HttpGet("GecikmeleriSifirla")]
        public EmptyResult GecikmeleriSifirla(string hesapKodu)
        {
            var fisList = _appDbContext.Fis
                                           .Include(y => y.HesapPlani)
                                           .Where(y => y.HesapPlani.Kod == hesapKodu)
                                           .OrderBy(c => c.Tarih).ThenBy(n => n.Id)
                                           .ToList();

            foreach (var item in fisList)
            {
                item.GecikmeGunu = 0;
                item.GecikmeTutari = 0;
                item.GeciktirilenAnaFaizTutar = 0;
                item.Odendi = false;
                item.KalanTutar = 0;
                
                item.OdenenBorcTutar = 0;
                item.KalanAlacakTutar = 0;
                item.KalanBorcTutar = 0;
                item.ZamanindaOdenenTutar = 0;
                item.ZamanindaOdemeTarihi = null;
                item.SonHesaplananGecikmeTarihi = null;
                item.GeciktirilenTutar = 0;
                _appDbContext.SaveChanges();
            }

            return new EmptyResult();
        }
    }
}

Oxit.Web.Admin/Views/Cari/Index.cshtml
@using Oxit.Domain.Models
@model Dictionary<string, object>
@{

    HesapPlani hesapPlani = (HesapPlani)Model["hesapPlani"];
    List<Fis> fisList = (List<Fis>)Model["fisList"];
    int pageCount = (int)Model["pageCount"];
    int page = (int)Model["page"];
    int alacakIdd = 0;
    double totalBorc = 0.00;
    double totalBakiye = 0.00;
    string Fistur = "";

    double totalAlacak = 0.00;
    double totalGecikmeTutari = 0.00;
    double totalOdenenGecikmeTutari = 0.00;
    double totalkalanGecikmeTutari = 0.00;

    ViewData["Title"] = "Şirketler | "+hesapPlani.Ad;
}
<div class="callout @(hesapPlani.Aktif ? "callout-success" : "callout-danger")  bg-white" style="border-left-width: 8px;">
    <h4>@hesapPlani.Ad</h4>
</div>


<div class="card text-center">
    <div class="card-header non-printable">
        @* <button class="btn btn-sm btn-light" type="button" id="gecikmeBorcHesapla" onclick="gecikmeBorcHesapla()">Borç Tutarı Gecikme Hesapla</button> *@
        @* <button class="btn btn-sm btn-success" type="button" id="gecikmeHesapla" onclick="gecikmeHesapla()">Gecikme Hesapla</button> *@
        @*  <button class="btn btn-sm btn-danger" type="button" id="gecikmeHesapla" onclick="gecikmeleriSifirla()">Gecikmeleri Sıfırla</button> *@
        @* <a class="btn btn-sm btn-info" href="@Url.Action("Edit","Cari",new {hesapId = hesapPlani.Id ,page = page})">Düzenle</a> *@
        @* <a class="btn btn-sm btn-warning" href="@Url.Action("Index","Companies")">Geri Dön</a> *@
        <button class="btn btn-sm btn-info float-end" type="button" onclick="window.print();">Yazdır</button>
        <a class="btn btn-sm btn-warning float-end me-1 ms-1" href="@Url.Action("DownloadExcel","Cari",new {hesapId = hesapPlani.Id })">Excel İndir</a>
    </div>
  <div class="card-body">
      <table class="table table-striped table-hover printable">
          <thead>
          <tr>
              <th scope="col" style="width: 70px;">Tür</th>
              
              <th scope="col" style="width: 70px;">Tarih</th>
              <th scope="col" style="width: 70px;">Borç</th>
              <th scope="col" style="width: 70px;">Alacak</th>
                <th scope="col" style="width: 70px;">Ek Aciklama</th>
              <th scope="col" style="width: 70px;">Gecikme T.</th>
              <th scope="col" style="width: 70px;">Gecikme Gn</th>
              @* <th scope="col">Açıklama</th> *@
              <th scope="col" style="width: 80px;">Hesap Tarihi</th>
              <th scope="col" style="width: 80px;">Ödn Borc Tutar</th>
              <th scope="col" style="width: 80px;">Kalan Borc Tutar</th>
              <th scope="col" style="width: 80px;">Odn Geckm Tutar</th>
              <th scope="col" style="width: 80px;">Kalan Gecikme Tutar</th>
              <th scope="col" style="width: 80px;">Kalan Alck Tutar</th>
          

          </tr>
          </thead>
          <tbody>
          @foreach (var f in fisList)
          {
              totalBorc = (f.Borc != null && f.FisTur != "6") ? totalBorc + (double)f.Borc : totalBorc;
              totalAlacak = f.Alacak != null ? totalAlacak + (double)f.Alacak : totalAlacak;
              totalGecikmeTutari = f.GecikmeTutari != null ? totalGecikmeTutari + (double)f.GecikmeTutari : totalGecikmeTutari;
              totalOdenenGecikmeTutari = f.OdenenGecikmeTutar != null ? totalOdenenGecikmeTutari + (double)f.OdenenGecikmeTutar : totalOdenenGecikmeTutari;
              totalkalanGecikmeTutari = f.KalanGecikmeTutar != null ? totalkalanGecikmeTutari + (double)f.KalanGecikmeTutar : totalkalanGecikmeTutari;

              string selectedClass = "";
              if (!f.Odendi && f.GecikmeTutari< 0)
              {
                  selectedClass = "white";
              }
              else if (f.Borc> 0 )
              {
                  selectedClass = "#3399FF";
                  Fistur = "Borç";
                  
                  if (f.FisTur == "0")
                      Fistur = "Açılış ";
                  if (f.FisTur == "6")
                  {
                      Fistur = " Bakiye ";
                      selectedClass = "#97BFE8";
                  }
                  if (f.FisTur == "9")
                  {
                      Fistur = " Gecikme Ft. ";
                      selectedClass = "#CA5CDD";
                  }
              }else  if (f.Alacak> 0)
              {
                  selectedClass = "#00CC00";
                  Fistur = "Alacak ";
              }
              else if (f.GecikmeTutari> 0 )
              {
                  selectedClass = "FF9900";
                  Fistur = "Gecikme ";
                  

                  
                  if (f.FisTur == "7") 
                  {
                      Fistur = "Gck - Bakiye ";
                      selectedClass = "#FFA000";
                  }   
                  if (f.Odendi)
                  {
                     
                      selectedClass = "#FFC56D";
                  }
                      

              }
              <tr bgcolor="@selectedClass">
                  <td>@(Fistur)</td>
                  <td>@Convert.ToDateTime(f.Tarih).ToString("dd.MM.yyyy")</td>
                  <td>@Convert.ToDouble(f.Borc).ToString("n2")@(f.Borc != null ? " ₺ " : "")</td>
                  <td>@Convert.ToDouble(f.Alacak).ToString("n2")@(f.Alacak != null ? " ₺ " : "")</td>
                  <td>@f.EkAciklama</td>
                  <td>@Convert.ToDouble(f.GecikmeTutari).ToString("n2")@(f.GecikmeTutari != null ? " ₺ " : "")</td>
                  <td>@Html.DisplayFor(m => f.GecikmeGunu)</td>
                  <td>
                      @if (f.SonHesaplananGecikmeTarihi != null)
                      {
                          @Convert.ToDateTime(f.SonHesaplananGecikmeTarihi).ToString("dd.MM.yyyy")
                      }
                  </td>
                  <td>@Convert.ToDouble(f.OdenenBorcTutar).ToString("n2")@(f.OdenenBorcTutar != null ? " ₺ " : "")</td>
                  <td>@Convert.ToDouble(f.KalanBorcTutar).ToString("n2")@(f.KalanBorcTutar != null ? " ₺ " : "")</td>
                  <td>@Convert.ToDouble(f.OdenenGecikmeTutar).ToString("n2")@(f.OdenenGecikmeTutar != null ? " ₺ " : "")</td>
                  <td>@Convert.ToDouble(f.KalanGecikmeTutar).ToString("n2")@(f.KalanGecikmeTutar != null ? " ₺ " : "")</td>
                  <td>@Convert.ToDouble(f.KalanAlacakTutar).ToString("n2")@(f.KalanAlacakTutar != null ? " ₺ " : "")</td>
                  <td>
                       @if (f.Alacak > 0)
                                            {
                                                <a data-toggle="modal" data-target="#partialModal" title="delete"
                                                   class="btn btn-danger btn-xs" onclick="Func_LoadPv(@f.Id)">Detay</a>
                                            }
                      
                  </td>
              </tr>
              totalBakiye = totalBorc - totalAlacak;

          }
          
          </tbody>
     
      </table>
  <div id="partialModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog"  role="document">
              <div class="modal-content">
                  <div class="modal-header">
                  
                      <h5 class="modal-title">Alacak Borc Ödeme Form</h5>
        
                  </div>
                  <div class="modal-body">
                  </div>
                  <div class="modal-footer">
                          <button type="button" class="btn btn-info" id="closbtn" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
      </div>
      <br/>
      
     
      <table style="background-color: lightblue;width:80%">
                 
                        <tr>
                            <td style="padding: 10px"> Borç</td>
                            <td style="padding: 10px"> Alacak </td>
                            <td style="padding: 10px"> Bakiye</td>
                            <td style="padding: 10px"> Gecikme</td>
                            <td style="padding: 10px">Ödenen Gecikme</td>
                            <td style="padding: 10px">Kalan Gecikme</td>
                        </tr>
                        <tr>
                         
                            <td style="padding: 10px">@totalBorc.ToString("n2")@(totalBorc != null ? " ₺ " : "")</td>
                           
                            <td style="padding: 10px">@totalAlacak.ToString("n2")@(totalAlacak != null ? " ₺ " : "")</td>
                            <td style="padding: 10px">@totalBakiye.ToString("n2")@(totalBakiye != null ? " ₺ " : "")</td>
                            
                            <td style="padding: 10px">@totalGecikmeTutari.ToString("n2")@(totalGecikmeTutari != null ? " ₺ " : "")</td>
                            <td style="padding: 10px">@totalOdenenGecikmeTutari.ToString("n2")@(totalOdenenGecikmeTutari != null ? " ₺ " : "")</td>
                            <td style="padding: 10px">@totalkalanGecikmeTutari.ToString("n2")@(totalkalanGecikmeTutari != null ? " ₺ " : "")</td>
                            </tr>
          
                    </table>
      
  </div>
</div>


<nav aria-label="Page navigation example non-printable">
    <ul class="pagination non-printable">
        @if (page>1)
        {
            <li class="page-item non-printable"><a class="page-link" href="@Url.Action("Index","Cari",new {hesapId = hesapPlani.Id ,page = page-1})" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
        }
        
        @for (int i = 1; i<=pageCount;i++)
        {
            <li class="page-item non-printable"><a class="page-link" href="@Url.Action("Index","Cari",new {hesapId = hesapPlani.Id ,page = i})">@i</a></li>
        }
        
        @if (page < pageCount)
        {
            <li class="page-item non-printable"><a class="page-link" href="@Url.Action("Index","Cari",new {hesapId = hesapPlani.Id ,page = page+1})" aria-label="Next"><span aria-hidden="true">»</span></a></li>
        }
    </ul>
</nav>

<script>
function gecikmeHesapla(){
    $.ajax({
                 type: "get",
                 url: "@Url.Action("GecikmeleriHesapla","GecikmeHesapla", new {hesapKodu = hesapPlani.Kod})",
                 dataType:"json",
                 success: function(response){
                     window.location.reload();
                 },
                 error: function(jqXHR){
                     if (jqXHR.status != 200) {
                         alert("Geçikmeler hesaplanamdı!");
                     }else{
                         window.location.reload();
                     }
                 }
        });
}



  $("#closbtn").click(function () {  

            $('#partialModal').modal('hide');  
        });        
    function gecikmeBorcHesapla() {
        $.ajax({
            type: "get",
            url: "@Url.Action("AlacaksizGecikmeHesapla", "GecikmeHesapla", new {hesapKodu = hesapPlani.Kod})",
            dataType: "json",
            success: function (response) {
                window.location.reload();
            },
            error: function (jqXHR) {
                if (jqXHR.status != 200) {
                    alert("Geçikmeler hesaplanamdı!");
                } else {
                    window.location.reload();
                }
            }
        });
    }
    
    $("partialModal").on('hide.bs.modal', function(){
    	alert('asd');
 
    });
              
       function Func_LoadPv(_alacakliId) {
   
    //  $.ajax({
    //                     type: "GET",
    //                     url: "/Cari/detailData",
    //                     data: '{alacakId: "' + alacakIdd + '" }',
    //                     contentType: "application/json; charset=utf-8",
    //                     dataType: "html",
    //                     success: function (response) {
    //                         alert(response);
    //                         $("#partialModal").find(".modal-body").html(response);
    //                         $("#partialModal").modal('show');
    //                     },
    //                     failure: function (response) {
    //                         alert(response.responseText);
    //                     },
    //                     error: function (response) {
    //                         alert(response.responseText);
    //                     }
    //                 });
    //       
    // // alert(_alacakliId);
    alacakIdd = _alacakliId;
        $.ajax({

                   type: "get",
                             url: "@Url.Action("detailData","Cari")",
                             dataType: "html",
                              contentType: "application/json; charset=utf-8",
                               data: { alacakId: alacakIdd },
                               success: function (response) {
                                                           $("#partialModal").find(".modal-body").html(response);
                                                           $("#partialModal").modal('show');
                                                       }

            
           });
            }
    function gecikmeleriSifirla() {
        $.ajax({
            type: "get",
            url: "@Url.Action("GecikmeleriSifirla","GecikmeHesapla", new {hesapKodu = hesapPlani.Kod})",
            dataType: "json",
            success: function (response) {
                window.location.reload();
            },
            error: function (jqXHR) {
                if (jqXHR.status != 200) {
                    alert("Geçikmeler sıfırlanamadı!");
                } else {
                    window.location.reload();
                }
            }
        });
    }

</script>

Oxit.Web.Admin/Views/Cari/detailData.cshtml
@using Oxit.Domain.Models
@model Dictionary<string, object>
@{
    List<Fis> fisList = (List<Fis>)Model["fisList"];
    Layout = null;
}
<table class="table table-striped table-hover printable">
    <thead>
    <tr>
        <th scope="col" style="width: 70px;">Tip</th>
        <th scope="col" style="width: 70px;">Tarih</th>
        <th scope="col" style="width: 70px;">Fatura No</th>
        <th scope="col" style="width: 70px;">Ödenen Tutar</th>

    </tr>
    </thead>
    <tbody>
    @foreach (var f in fisList)
    {
        <tr >
              <td>
                             @if (f.OdenenBorcTutar > 0)
                             {
                                 @Convert.ToString("Borç")
                             }
                             else
                                  {
                                      @Convert.ToString("Gecikme")
                                   }
                            
                            
                        </td>
            <td>@Convert.ToDateTime(f.Tarih).ToString("dd.MM.yyyy")</td>
            <td>@f.EkAciklama</td>
            <td>
                @if (f.OdenenBorcTutar > 0)
                {
                    @Convert.ToDouble(f.OdenenBorcTutar).ToString("n2")@(f.OdenenBorcTutar != null ? " ₺ " : "")
                }
                else
                {
                    @Convert.ToDouble(f.OdenenGecikmeTutar).ToString("n2")@(f.OdenenGecikmeTutar != null ? " ₺ " : "")
                }


            </td>
        </tr>
    }
    </tbody>
     
</table>

Oxit.Web.Admin/Views/Cari/edit.cshtml
@using Oxit.Domain.Models
@model Dictionary<string, object>
@{
    
    HesapPlani hesapPlani = (HesapPlani)Model["hesapPlani"];
    List<Fis> fisList = (List<Fis>)Model["fisList"];
    int pageCount = (int)Model["pageCount"];
    int page = (int)Model["page"];
    
    ViewData["Title"] = "Şirketler | "+hesapPlani.Ad;
}
<div class="callout @(hesapPlani.Aktif ? "callout-success" : "callout-danger")  bg-white" style="border-left-width: 8px;">
    <h4>@hesapPlani.Ad</h4>
</div>


<div class="card text-center">
  <div class="card-header">
      <a class="btn btn-sm btn-info" href="@Url.Action("Index","Cari",new {hesapId = hesapPlani.Id ,page = page})">Geri Dön</a>
  </div>
  <div class="card-body">
        <table class="table table-striped table-hover">
          <thead>
              <tr>
                  <th scope="col">Fiş Türü</th>
                  <th scope="col">Tarih</th>
                  <th scope="col">Borç</th>
                  <th scope="col">Alacak</th>
                  <th scope="col">Açıklama</th>
              </tr>
          </thead>
          <tbody>
              
              @foreach (var f in fisList)
              {
                  string selectedClass = "";
                  if (!f.Odendi)
                  {
                      selectedClass = "white";
                  }
                  else
                  {
                      selectedClass = "green";
                  }

                  <tr bgcolor="@selectedClass">
                      <th scope="row">
                          <select class="form-select" aria-label="Default select example" onchange="comboChange(this,@f.Id)">
                              <!option @(f.FisTip == null ? "selected" : "")>Kayıt Türü Seçiniz</!option>
                              <!option @(f.FisTip == FisTip.KiraFaturasi ? "selected" : "") value="0">Kira Faturası</!option>
                              <!option @(f.FisTip == FisTip.KiraOdemesi ? "selected" : "") value="3">Kira Ödemesi</!option>
                              <!option @(f.FisTip == FisTip.Proje ? "selected" : "") value="1">Proje</!option>
                              <!option @(f.FisTip == FisTip.Diger ? "selected" : "") value="2">Diğer</!option>
                          </select>
                      </th>
                      <td>@Html.DisplayFor(m => f.Tarih, "dd.MM.yyyy")</td>
                      <td>@Html.DisplayFor(modelItem => f.Borc)@(f.Borc != null? " ₺":"")</td>
                      <td>@Html.DisplayFor(modelItem => f.Alacak)@(f.Alacak != null? " ₺":"")</td>
                      <td>@Html.DisplayFor(modelItem => f.Aciklama)</td>
                      <td></td>
                      <td></td>
                  </tr>
              }
          </tbody>
        </table>
</div>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        @if (page>1)
        {
            <li class="page-item"><a class="page-link" href="@Url.Action("Edit","Cari",new {hesapId = hesapPlani.Id ,page = page-1})" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
        }
        
        @for (int i = 1; i<=pageCount;i++)
        {
            <li class="page-item"><a class="page-link" href="@Url.Action("Edit","Cari",new {hesapId = hesapPlani.Id ,page = i})">@i</a></li>
        }
        
        @if (page < pageCount)
        {
            <li class="page-item"><a class="page-link" href="@Url.Action("Edit","Cari",new {hesapId = hesapPlani.Id ,page = page+1})" aria-label="Next"><span aria-hidden="true">»</span></a></li>
        }
    </ul>
</nav>

<script>
function comboChange(this_,fisId){
    $.ajax({
             type: "post",
             url: "@Url.Action("saveStatus","Cari")",
             data: { fisId: fisId, status:$(this_).val()},
             dataType:"json",
             success: function(response){
               
             },
             error: function(response){
               
             }
    });
}
</script>